ktor:
  application:
    modules:
      - org.bscm.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: "$PORT:8080"
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: $POSTGRES_URL
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
jwt:
  secret: $JWT_SECRET
  realm: "bs-community"
hmac:
  secret: $HMAC_SECRET
discord:
  clientId: $DISCORD_CLIENT_ID
  clientSecret: $DISCORD_CLIENT_SECRET
  redirectUri: $DISCORD_REDIRECT_URI
  webhookId: $DISCORD_WEBHOOK_ID
  webhookToken: $DISCORD_WEBHOOK_TOKEN
  botToken: $DISCORD_BOT_TOKEN
  channelId: $DISCORD_CHANNEL_ID
google:
  clientId: $GOOGLE_CLIENT_ID
  clientSecret: $GOOGLE_CLIENT_SECRET
  redirectUri: $GOOGLE_REDIRECT_URI
status:
  url: $STATUS_URL
