ktor:
  application:
    modules:
      - org.bscm.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: "$PORT:8080"
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: $POSTGRES_URL
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
jwt:
  secret: $JWT_SECRET
  realm: "bs-community"
