CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, image_url VARCHAR(255) NULL, banner_url VARCHAR(255) NULL, avatar_url VARCHAR(255) NULL, accent_color INT NULL, bio TEXT NULL, is_public BOOLEAN DEFAULT TRUE NOT NULL, "role" VARCHAR(20) DEFAULT 'USER' NOT NULL, is_verified BOOLEAN DEFAULT FALSE NOT NULL, verified_at TIMESTAMP NULL, verified_by uuid NULL, follower_count INT DEFAULT 0 NOT NULL, following_count INT DEFAULT 0 NOT NULL, discord_id VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL);
ALTER TABLE users ADD CONSTRAINT users_username_unique UNIQUE (username);
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT users_discord_id_unique UNIQUE (discord_id);
CREATE TABLE IF NOT EXISTS accounts (id uuid PRIMARY KEY, provider VARCHAR(50) NOT NULL, refresh_token VARCHAR(255) NULL, access_token VARCHAR(255) NULL, expires_at TIMESTAMP NULL, token_type VARCHAR(50) NULL, scope VARCHAR(255) NULL, user_id uuid NOT NULL);
CREATE INDEX accounts_user_id ON accounts (user_id);
ALTER TABLE accounts ADD CONSTRAINT accounts_provider_user_id_unique UNIQUE (provider, user_id);
CREATE TABLE IF NOT EXISTS badges (id uuid PRIMARY KEY, "name" VARCHAR(255) NOT NULL, description TEXT NULL, criteria TEXT NULL, created_at TIMESTAMP NOT NULL);
ALTER TABLE badges ADD CONSTRAINT badges_name_unique UNIQUE ("name");
CREATE TABLE IF NOT EXISTS catalog_item_versions (id BIGSERIAL PRIMARY KEY, catalog_item_id VARCHAR(10) NOT NULL, version_code INT NOT NULL, downloads_amount INT DEFAULT 0 NOT NULL, file_size_bytes BIGINT NOT NULL, changelog TEXT NULL, discord_attachment_id VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL);
CREATE INDEX catalog_item_versions_catalog_item_id ON catalog_item_versions (catalog_item_id);
ALTER TABLE catalog_item_versions ADD CONSTRAINT catalog_item_versions_catalog_item_id_version_code_unique UNIQUE (catalog_item_id, version_code);
CREATE TABLE IF NOT EXISTS catalog_items (id VARCHAR(10) PRIMARY KEY, "type" VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, visibility VARCHAR(20) DEFAULT 'PUBLIC' NOT NULL, versions_count INT DEFAULT 0 NOT NULL, latest_version_id BIGINT NULL, preview_video_id VARCHAR(12) NULL, is_featured BOOLEAN DEFAULT FALSE NOT NULL, downloads_sum INT DEFAULT 0 NOT NULL, discord_channel_id VARCHAR(255) NULL, discord_message_id VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL, published_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, bundle_hash VARCHAR(64) NULL, author_id uuid NULL);
CREATE INDEX catalog_items_type ON catalog_items ("type");
CREATE INDEX catalog_items_status ON catalog_items (status);
CREATE INDEX catalog_items_author_id ON catalog_items (author_id);
ALTER TABLE catalog_items ADD CONSTRAINT catalog_items_bundle_hash_unique UNIQUE (bundle_hash);
CREATE TABLE IF NOT EXISTS bundle_url_cache (catalog_item_id VARCHAR(10) PRIMARY KEY, bundle_url TEXT NOT NULL, expires_at TIMESTAMP NOT NULL, last_validated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS tracks (id uuid PRIMARY KEY, title VARCHAR(200) NOT NULL, artist VARCHAR(100) NOT NULL, album VARCHAR(200) NULL, isrc VARCHAR(15) NULL, genres VARCHAR(255)[255] NULL, bpm INT NULL, duration REAL NOT NULL, normalized_title VARCHAR(200) NULL, normalized_artist VARCHAR(200) NULL, normalized_album VARCHAR(200) NULL);
CREATE INDEX tracks_normalized_title ON tracks (normalized_title);
CREATE INDEX tracks_normalized_artist ON tracks (normalized_artist);
CREATE INDEX tracks_normalized_album ON tracks (normalized_album);
CREATE TABLE IF NOT EXISTS charts (id VARCHAR(10) PRIMARY KEY, track_id uuid NOT NULL, difficulty VARCHAR(10) NOT NULL, notes_amount INT NOT NULL, effects_amount INT NOT NULL, is_deluxe BOOLEAN DEFAULT FALSE NOT NULL, is_explicit BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT fk_charts_track_id__id FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS changelogs (id uuid PRIMARY KEY, chart_id VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(1000) NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_changelogs_chart_id__id FOREIGN KEY (chart_id) REFERENCES charts(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS collections (id uuid PRIMARY KEY, user_id uuid NOT NULL, kind VARCHAR(20) DEFAULT 'USER' NOT NULL, slug VARCHAR(30) NULL, "name" VARCHAR(30) NOT NULL, is_public BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
ALTER TABLE collections ADD CONSTRAINT collections_slug_unique UNIQUE (slug);
ALTER TABLE collections ADD CONSTRAINT collections_user_id_name_unique UNIQUE (user_id, "name");
CREATE TABLE IF NOT EXISTS collection_items (id SERIAL PRIMARY KEY, collection_id uuid NOT NULL, content_id VARCHAR(10) NOT NULL, added_at TIMESTAMP NOT NULL);
CREATE INDEX collection_items_collection_id_added_at_content_id ON collection_items (collection_id, added_at, content_id);
ALTER TABLE collection_items ADD CONSTRAINT collection_items_collection_id_content_id_unique UNIQUE (collection_id, content_id);
CREATE TABLE IF NOT EXISTS contributors (id BIGSERIAL PRIMARY KEY, catalog_item_id VARCHAR(10) NOT NULL, user_id uuid NOT NULL, "role" VARCHAR(30) NOT NULL, note VARCHAR(280) NULL, joined_at TIMESTAMP NOT NULL);
ALTER TABLE contributors ADD CONSTRAINT contributors_catalog_item_id_user_id_role_unique UNIQUE (catalog_item_id, user_id, "role");
CREATE TABLE IF NOT EXISTS themes (id VARCHAR(10) PRIMARY KEY, "name" VARCHAR(255) NOT NULL, replaces VARCHAR(255) NOT NULL, display_art_url VARCHAR(512) NULL, preview_url VARCHAR(512) NULL, cover_url VARCHAR(512) NULL);
CREATE INDEX themes_name ON themes ("name");
CREATE TABLE IF NOT EXISTS tour_passes (id VARCHAR(10) PRIMARY KEY, "name" VARCHAR(255) NOT NULL, description VARCHAR(500) NULL, artist VARCHAR(255) NULL, cover_id VARCHAR(10) NULL);
CREATE TABLE IF NOT EXISTS tour_pass_charts (tour_pass_id VARCHAR(10), chart_id VARCHAR(10), "position" INT DEFAULT 0 NOT NULL, CONSTRAINT pk_tour_pass_charts PRIMARY KEY (tour_pass_id, chart_id), CONSTRAINT fk_tour_pass_charts_tour_pass_id__id FOREIGN KEY (tour_pass_id) REFERENCES tour_passes(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_tour_pass_charts_chart_id__id FOREIGN KEY (chart_id) REFERENCES charts(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX tour_pass_charts_tour_pass_id_position ON tour_pass_charts (tour_pass_id, "position");
CREATE TABLE IF NOT EXISTS track_streaming_refs (id BIGSERIAL PRIMARY KEY, track_id uuid NOT NULL, platform VARCHAR(30) NOT NULL, external_id VARCHAR(128) NOT NULL, CONSTRAINT fk_track_streaming_refs_track_id__id FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE track_streaming_refs ADD CONSTRAINT track_streaming_refs_external_id_unique UNIQUE (external_id);
ALTER TABLE track_streaming_refs ADD CONSTRAINT track_streaming_refs_track_id_platform_unique UNIQUE (track_id, platform);
ALTER TABLE track_streaming_refs ADD CONSTRAINT track_streaming_refs_platform_external_id_unique UNIQUE (platform, external_id);
CREATE TABLE IF NOT EXISTS user_activity (id uuid PRIMARY KEY, user_id uuid NOT NULL, "type" VARCHAR(30) NOT NULL, target_id VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE INDEX user_activity_user_id_created_at ON user_activity (user_id, created_at);
CREATE TABLE IF NOT EXISTS user_badges (user_id uuid, badge_id uuid, granted_at TIMESTAMP NOT NULL, granted_by uuid NULL, CONSTRAINT pk_user_badges PRIMARY KEY (user_id, badge_id));
CREATE INDEX user_badges_user_id ON user_badges (user_id);
CREATE INDEX user_badges_badge_id ON user_badges (badge_id);
CREATE TABLE IF NOT EXISTS user_follows (follower_id uuid, followed_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_user_follows PRIMARY KEY (follower_id, followed_id));
CREATE INDEX user_follows_follower_id ON user_follows (follower_id);
CREATE INDEX user_follows_followed_id ON user_follows (followed_id);
ALTER TABLE users ADD CONSTRAINT fk_users_verified_by__id FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE accounts ADD CONSTRAINT fk_accounts_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE catalog_item_versions ADD CONSTRAINT fk_catalog_item_versions_catalog_item_id__id FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE catalog_items ADD CONSTRAINT fk_catalog_items_latest_version_id__id FOREIGN KEY (latest_version_id) REFERENCES catalog_item_versions(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE catalog_items ADD CONSTRAINT fk_catalog_items_author_id__id FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE bundle_url_cache ADD CONSTRAINT fk_bundle_url_cache_catalog_item_id__id FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE collections ADD CONSTRAINT fk_collections_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE collection_items ADD CONSTRAINT fk_collection_items_collection_id__id FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE collection_items ADD CONSTRAINT fk_collection_items_content_id__id FOREIGN KEY (content_id) REFERENCES catalog_items(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE contributors ADD CONSTRAINT fk_contributors_catalog_item_id__id FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE contributors ADD CONSTRAINT fk_contributors_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE user_activity ADD CONSTRAINT fk_user_activity_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_badge_id__id FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_granted_by__id FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_follows ADD CONSTRAINT fk_user_follows_follower_id__id FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE user_follows ADD CONSTRAINT fk_user_follows_followed_id__id FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
CREATE SEQUENCE IF NOT EXISTS collection_items_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS contributors_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS track_streaming_refs_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS catalog_item_versions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;