ALTER TABLE contributors ALTER COLUMN joined_at TYPE TIMESTAMP, ALTER COLUMN joined_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP, ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE versions ALTER COLUMN published_at TYPE TIMESTAMP, ALTER COLUMN published_at SET DEFAULT CURRENT_TIMESTAMP;
