CREATE TABLE IF NOT EXISTS badges (id uuid PRIMARY KEY, "name" VARCHAR(255) NOT NULL, description TEXT NULL, criteria TEXT NULL, created_at TIMESTAMP NOT NULL);
ALTER TABLE badges ADD CONSTRAINT badges_name_unique UNIQUE ("name");
CREATE TABLE IF NOT EXISTS user_activity (id uuid PRIMARY KEY, user_id uuid NOT NULL, "type" VARCHAR(30) NOT NULL, target_id VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE INDEX user_activity_user_id_created_at ON user_activity (user_id, created_at);
CREATE TABLE IF NOT EXISTS user_badges (user_id uuid, badge_id uuid, granted_at TIMESTAMP NOT NULL, granted_by uuid NULL, CONSTRAINT pk_user_badges PRIMARY KEY (user_id, badge_id));
CREATE INDEX user_badges_user_id ON user_badges (user_id);
CREATE INDEX user_badges_badge_id ON user_badges (badge_id);
CREATE TABLE IF NOT EXISTS user_follows (follower_id uuid, followed_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_user_follows PRIMARY KEY (follower_id, followed_id));
CREATE INDEX user_follows_follower_id ON user_follows (follower_id);
CREATE INDEX user_follows_followed_id ON user_follows (followed_id);
ALTER TABLE user_activity ADD CONSTRAINT fk_user_activity_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_badge_id__id FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_badges ADD CONSTRAINT fk_user_badges_granted_by__id FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_follows ADD CONSTRAINT fk_user_follows_follower_id__id FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE user_follows ADD CONSTRAINT fk_user_follows_followed_id__id FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE charts ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE charts ADD updated_at TIMESTAMP NULL;
ALTER TABLE charts ADD preview_provider VARCHAR(20) NULL;
ALTER TABLE charts ADD preview_provider_track_id VARCHAR(100) NULL;
ALTER TABLE collections ADD kind VARCHAR(20) DEFAULT 'USER' NOT NULL;
ALTER TABLE collections ADD CONSTRAINT collections_user_id_kind_unique UNIQUE (user_id, kind);
ALTER TABLE contributors ADD note VARCHAR(280) NULL;
ALTER TABLE themes ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE themes ADD updated_at TIMESTAMP NULL;
ALTER TABLE tour_passes ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE tour_passes ADD updated_at TIMESTAMP NULL;
ALTER TABLE users ADD banner_url VARCHAR(255) NULL;
ALTER TABLE users ADD avatar_url VARCHAR(255) NULL;
ALTER TABLE users ADD accent_color INT NULL;
ALTER TABLE users ADD bio TEXT NULL;
ALTER TABLE users ADD is_public BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE users ADD "role" VARCHAR(20) DEFAULT 'USER' NOT NULL;
ALTER TABLE users ADD is_verified BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD verified_at TIMESTAMP NULL;
ALTER TABLE users ADD verified_by uuid NULL;
ALTER TABLE users ADD follower_count INT DEFAULT 0 NOT NULL;
ALTER TABLE users ADD following_count INT DEFAULT 0 NOT NULL;
ALTER TABLE versions ADD changelog JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE versions RENAME COLUMN published_at TO created_at;
ALTER TABLE versions ADD CONSTRAINT versions_chart_id_created_at_unique UNIQUE (chart_id, created_at);
ALTER TABLE users ADD CONSTRAINT fk_users_verified_by__id FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE versions DROP COLUMN "index";
ALTER TABLE versions DROP COLUMN known_issues;
CREATE INDEX collection_items_collection_id_added_at_content_id ON collection_items (collection_id, added_at, content_id);
DROP INDEX IF EXISTS collection_items_content_id;
DROP INDEX IF EXISTS collection_items_collection_id;
DROP INDEX IF EXISTS versions_downloads_amount;
