ALTER TABLE charts ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE charts ADD updated_at TIMESTAMP NULL;
ALTER TABLE themes ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE themes ADD updated_at TIMESTAMP NULL;
ALTER TABLE tour_passes ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE tour_passes ADD updated_at TIMESTAMP NULL;
